# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, default=18.735693, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, default=-70.162651, max_digits=9, verbose_name='Longitude')),
                ('nickname', models.CharField(default='', max_length=30, verbose_name='client')),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('nickname',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='client')),
                ('phone_number', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Fall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallen_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('crater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crater_finder.Crater')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crater_finder.Employee')),
            ],
            options={
                'ordering': ('-fallen_at',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Compact', 'Compact'), ('Sport', 'Sport')], default='Sedan', max_length=10)),
                ('plate', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('plate',),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crater_finder.Vehicle'),
        ),
        migrations.AddField(
            model_name='crater',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crater_finder.Employee'),
        ),
    ]
