# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crater_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crater',
            name='nickname',
            field=models.CharField(default='', max_length=30, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='name'),
        ),
    ]
