# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crater_finder', '0002_auto_20170303_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crater',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='crater',
            name='reported_by',
        ),
    ]
